import { createInMemoryArenaRepository } from "@/lib/server/in-memory-arena-repository";
import type { ArenaState } from "@/lib/server/types";

const CURRENT_TIME = "2026-03-10T18:00:00.000Z";

function createMockArenaState(): ArenaState {
  return {
    profiles: [
      {
        id: "builder-1",
        email: "admin@example.com",
        displayName: "Vera Flux",
        username: "veraflux",
        avatarUrl: null,
        authProvider: "mock",
        foundingBuilder: true,
        createdAt: CURRENT_TIME,
      },
      {
        id: "builder-2",
        email: "loops@example.com",
        displayName: "Noah Loops",
        username: "noahloops",
        avatarUrl: null,
        authProvider: "mock",
        foundingBuilder: true,
        createdAt: CURRENT_TIME,
      },
      {
        id: "builder-3",
        email: "murmur@example.com",
        displayName: "Maya Murmur",
        username: "mayamurmur",
        avatarUrl: null,
        authProvider: "mock",
        foundingBuilder: true,
        createdAt: CURRENT_TIME,
      },
      {
        id: "builder-4",
        email: "sheriff@example.com",
        displayName: "Ivo Sheriff",
        username: "ivosheriff",
        avatarUrl: null,
        authProvider: "mock",
        foundingBuilder: false,
        createdAt: CURRENT_TIME,
      },
      {
        id: "builder-5",
        email: "solo@example.com",
        displayName: "Juno Draft",
        username: "junodraft",
        avatarUrl: null,
        authProvider: "mock",
        foundingBuilder: false,
        createdAt: CURRENT_TIME,
      },
    ],
    weeks: [
      {
        id: "week-current",
        slug: "agents-in-the-arena",
        themeTitle: "Agents in the Arena",
        themeDescription:
          "Build an AI app that feels competitive in the first 15 seconds.",
        timezone: "America/Los_Angeles",
        submissionOpenAt: "2026-03-06T20:00:00.000Z",
        submissionCloseAt: "2026-03-10T07:00:00.000Z",
        votingOpenAt: "2026-03-10T16:00:00.000Z",
        votingCloseAt: "2026-03-13T07:00:00.000Z",
        status: "voting_open",
      },
      {
        id: "week-past",
        slug: "voice-ui-showdown",
        themeTitle: "Voice UI Showdown",
        themeDescription:
          "Make a voice-first agent people want to use twice in one day.",
        timezone: "America/Los_Angeles",
        submissionOpenAt: "2026-02-27T20:00:00.000Z",
        submissionCloseAt: "2026-03-02T07:00:00.000Z",
        votingOpenAt: "2026-03-02T16:00:00.000Z",
        votingCloseAt: "2026-03-05T07:00:00.000Z",
        status: "locked",
      },
    ],
    entries: [
      {
        id: "entry-1",
        weekId: "week-current",
        builderId: "builder-1",
        slug: "prompt-forge",
        title: "Prompt Forge",
        oneLiner: "Stress-test prompts against real user friction before launch.",
        liveUrl: "https://prompt-forge.example.com",
        demoAssetPath: "mock://prompt-forge",
        status: "approved",
        eloRating: 1242,
        wins: 4,
        losses: 1,
        appearanceCount: 16,
        submittedAt: CURRENT_TIME,
        approvedAt: "2026-03-09T18:00:00.000Z",
      },
      {
        id: "entry-2",
        weekId: "week-current",
        builderId: "builder-2",
        slug: "crit-circuit",
        title: "Crit Circuit",
        oneLiner: "Pit two model critiques against each other to sharpen product decisions.",
        liveUrl: "https://crit-circuit.example.com",
        demoAssetPath: "mock://crit-circuit",
        status: "approved",
        eloRating: 1216,
        wins: 3,
        losses: 2,
        appearanceCount: 15,
        submittedAt: CURRENT_TIME,
        approvedAt: "2026-03-09T19:00:00.000Z",
      },
      {
        id: "entry-3",
        weekId: "week-current",
        builderId: "builder-3",
        slug: "murmur-qa",
        title: "Murmur QA",
        oneLiner: "Auto-generate trust-check interviews for every feature branch.",
        liveUrl: "https://murmur-qa.example.com",
        demoAssetPath: "mock://murmur-qa",
        status: "approved",
        eloRating: 1194,
        wins: 2,
        losses: 3,
        appearanceCount: 14,
        submittedAt: CURRENT_TIME,
        approvedAt: "2026-03-09T20:00:00.000Z",
      },
      {
        id: "entry-4",
        weekId: "week-current",
        builderId: "builder-4",
        slug: "screen-sheriff",
        title: "Screen Sheriff",
        oneLiner: "Watch UI sessions and flag the exact second trust falls apart.",
        liveUrl: "https://screen-sheriff.example.com",
        demoAssetPath: "mock://screen-sheriff",
        status: "approved",
        eloRating: 1148,
        wins: 1,
        losses: 4,
        appearanceCount: 15,
        submittedAt: CURRENT_TIME,
        approvedAt: "2026-03-09T21:00:00.000Z",
      },
      {
        id: "entry-5",
        weekId: "week-current",
        builderId: "builder-5",
        slug: "draft-surge",
        title: "Draft Surge",
        oneLiner: "Turn a cold product brief into a shippable MVP spec in 12 minutes.",
        liveUrl: "https://draft-surge.example.com",
        demoAssetPath: "mock://draft-surge",
        status: "approved",
        eloRating: 1186,
        wins: 2,
        losses: 4,
        appearanceCount: 13,
        submittedAt: CURRENT_TIME,
        approvedAt: "2026-03-09T22:00:00.000Z",
      },
      {
        id: "entry-past-1",
        weekId: "week-past",
        builderId: "builder-2",
        slug: "voice-loom",
        title: "Voice Loom",
        oneLiner: "Prototype phone-call agents with instant real-world objection scripts.",
        liveUrl: "https://voice-loom.example.com",
        demoAssetPath: "mock://voice-loom",
        status: "approved",
        eloRating: 1258,
        wins: 5,
        losses: 1,
        appearanceCount: 20,
        submittedAt: CURRENT_TIME,
        approvedAt: "2026-03-01T18:00:00.000Z",
      },
      {
        id: "entry-past-2",
        weekId: "week-past",
        builderId: "builder-3",
        slug: "reply-garden",
        title: "Reply Garden",
        oneLiner: "Grow voice replies from a seed phrase and a real customer mood.",
        liveUrl: "https://reply-garden.example.com",
        demoAssetPath: "mock://reply-garden",
        status: "approved",
        eloRating: 1188,
        wins: 3,
        losses: 3,
        appearanceCount: 19,
        submittedAt: CURRENT_TIME,
        approvedAt: "2026-03-01T19:00:00.000Z",
      },
      {
        id: "entry-past-3",
        weekId: "week-past",
        builderId: "builder-1",
        slug: "callsmith",
        title: "Callsmith",
        oneLiner: "Repair shaky sales calls with agent-generated counterfactuals.",
        liveUrl: "https://callsmith.example.com",
        demoAssetPath: "mock://callsmith",
        status: "approved",
        eloRating: 1154,
        wins: 1,
        losses: 5,
        appearanceCount: 18,
        submittedAt: CURRENT_TIME,
        approvedAt: "2026-03-01T20:00:00.000Z",
      },
    ],
    matchups: [
      {
        id: "matchup-entry-1-entry-2",
        weekId: "week-current",
        entryAId: "entry-1",
        entryBId: "entry-2",
        exposureCount: 9,
        voteCount: 7,
        createdAt: CURRENT_TIME,
      },
      {
        id: "matchup-entry-1-entry-3",
        weekId: "week-current",
        entryAId: "entry-1",
        entryBId: "entry-3",
        exposureCount: 8,
        voteCount: 6,
        createdAt: CURRENT_TIME,
      },
      {
        id: "matchup-entry-1-entry-4",
        weekId: "week-current",
        entryAId: "entry-1",
        entryBId: "entry-4",
        exposureCount: 8,
        voteCount: 6,
        createdAt: CURRENT_TIME,
      },
      {
        id: "matchup-entry-2-entry-3",
        weekId: "week-current",
        entryAId: "entry-2",
        entryBId: "entry-3",
        exposureCount: 7,
        voteCount: 5,
        createdAt: CURRENT_TIME,
      },
      {
        id: "matchup-entry-2-entry-4",
        weekId: "week-current",
        entryAId: "entry-2",
        entryBId: "entry-4",
        exposureCount: 7,
        voteCount: 5,
        createdAt: CURRENT_TIME,
      },
      {
        id: "matchup-entry-3-entry-4",
        weekId: "week-current",
        entryAId: "entry-3",
        entryBId: "entry-4",
        exposureCount: 6,
        voteCount: 4,
        createdAt: CURRENT_TIME,
      },
      {
        id: "matchup-entry-1-entry-5",
        weekId: "week-current",
        entryAId: "entry-1",
        entryBId: "entry-5",
        exposureCount: 7,
        voteCount: 5,
        createdAt: CURRENT_TIME,
      },
      {
        id: "matchup-entry-2-entry-5",
        weekId: "week-current",
        entryAId: "entry-2",
        entryBId: "entry-5",
        exposureCount: 6,
        voteCount: 4,
        createdAt: CURRENT_TIME,
      },
      {
        id: "matchup-entry-3-entry-5",
        weekId: "week-current",
        entryAId: "entry-3",
        entryBId: "entry-5",
        exposureCount: 6,
        voteCount: 4,
        createdAt: CURRENT_TIME,
      },
      {
        id: "matchup-entry-4-entry-5",
        weekId: "week-current",
        entryAId: "entry-4",
        entryBId: "entry-5",
        exposureCount: 5,
        voteCount: 3,
        createdAt: CURRENT_TIME,
      },
    ],
    voterSessions: [],
    votes: [],
  };
}

declare global {
  var __hubdevMockRepository:
    | ReturnType<typeof createInMemoryArenaRepository>
    | undefined;
}

export function getMockArenaRepository() {
  if (!globalThis.__hubdevMockRepository) {
    globalThis.__hubdevMockRepository = createInMemoryArenaRepository(
      createMockArenaState(),
    );
  }

  return globalThis.__hubdevMockRepository;
}

export function resetMockArenaRepository() {
  globalThis.__hubdevMockRepository = createInMemoryArenaRepository(
    createMockArenaState(),
  );
  return globalThis.__hubdevMockRepository;
}
